// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckComputerWin():Promise<boolean>;

export function CheckUserWin():Promise<boolean>;

export function ClearFields():Promise<void>;

export function GetFields():Promise<any>;

export function SetComputerMark():Promise<void>;

export function SetUserMark(arg1:number):Promise<boolean>;
