// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckComputerWin() {
  return window['go']['main']['App']['CheckComputerWin']();
}

export function CheckUserWin() {
  return window['go']['main']['App']['CheckUserWin']();
}

export function ClearFields() {
  return window['go']['main']['App']['ClearFields']();
}

export function GetFields() {
  return window['go']['main']['App']['GetFields']();
}

export function SetComputerMark() {
  return window['go']['main']['App']['SetComputerMark']();
}

export function SetUserMark(arg1) {
  return window['go']['main']['App']['SetUserMark'](arg1);
}
